INSERT INTO JOB VALUES('J7','신입사원');
INSERT INTO JOB VALUES(NULL,'주임');

DELETE FROM JOB
WHERE JOB_CODE = 'J1';

INSERT INTO JOB VALUES('J1', '사장');

DROP TABLE JOB;
CREATE TABLE JOB(
    JOB_CODE CHAR(2) UNIQUE,
    JOB_NAME VARCHAR2(35)
);

CREATE TABLE JOB(
    JOB_CODE CHAR(2) CONSTRAINT JOB_PK PRIMARY KEY,
    JOB_NAME VARCHAR(35)
);

INSERT INTO JOB VALUES('J1', '대표');
INSERT INTO JOB VALUES('J2', '부사장');
INSERT INTO JOB VALUES('J3', '부장');
INSERT INTO JOB VALUES('J4', '차장');
INSERT INTO JOB VALUES('J5', '과장');
INSERT INTO JOB VALUES('J6', '대리');
INSERT INTO JOB VALUES('J7', '사원');

--PRIMARY KEY 제약조건
-- NULL이 들어가지않고 중복도 되지않게하는 제약조건



INSERT INTO DEPARTMENT
VALUES (NULL, NULL, 'L1');

DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT(
    DEPT_ID CHAR(2)NOT NULL,
    DEPT_TITLE VARCHAR(35),
    LOCATION_ID CHAR(2)NOT NULL
);

-- 제약조건 삭제
ALTER TABLE DEPARTMENT
DROP CONSTRAINT SYS_C007004;

-- 제약조건 추가
ALTER TABLE DEPARTMENT
ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DEPT_ID);

ALTER TABLE DEPARTMENT
MODIFY DEPT_ID NOT NULL;
-- 제약조건 이름 변경
ALTER TABLE DEPARTMENT
RENAME CONSTRAINT DEPARTMENT_PK TO DEPT_ID_PK;


INSERT INTO DEPARTMENT VALUES (NULL, NULL,NULL);
INSERT INTO DEPARTMENT VALUES('D1','인사관리부','L1'); 
INSERT INTO DEPARTMENT VALUES('D2','회계관리부','L2');
INSERT INTO DEPARTMENT(DEPT_ID,DEPT_TITLE,LOCATION_ID)
VALUES('D3', '마케팅부', 'L1');
INSERT INTO DEPARTMENT
VALUES('D4', '국내영업부', 'L1');
INSERT INTO DEPARTMENT VALUES('D5', '해외영업1부', 'L2');
INSERT INTO DEPARTMENT VALUES('D6', '해외영업2부', 'L3');
INSERT INTO DEPARTMENT VALUES('D7', '해외영업3부', 'L4');
INSERT INTO DEPARTMENT VALUES('D8', '기술지원부', 'L5');
INSERT INTO DEPARTMENT VALUES('D9', '총무부', 'L1');



COMMENT ON COLUMN DEPARTMENT.DEPT_ID IS '부서코드';

DESC DEPARTMENT;

DESC DEPARTMENT;

ALTER TABLE DEPARTMENT
RENAME TO DEPARTMENT_TEST;

RENAME DEPARTMENT_TEST TO DEPARTMENT;

ALTER TABLE DEPARTMENT
MODIFY DEPT_CODE CHAR(3);

ALTER TABLE DEPARTMENT
RENAME COLUMN DEPT_ID TO DEPT_CODE;

ALTER TABLE DEPARTMENT
ADD DEPT_NAME VARCHAR2(30);

ALTER TABLE DEPARTMENT
DROP COLUMN DEPT_NAME;


ALTER TABLE LOCATION
ADD CONSTRAINT LOCAL_CODE_PK PRIMARY KEY(LOCAL_CODE);

ALTER TABLE LOCATION
MODIFY NATIONAL_CODE NOT NULL;

ALTER TABLE EMPLOYEE
RENAME COLUMN EPM_ID TO EMP_ID;
ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMP_ID_PK PRIMARY KEY(EMP_ID);

ALTER TABLE EMPLOYEE
MODIFY EMP_NAME NOT NULL;

ALTER TABLE EMPLOYEE
MODIFY EMP_NO NOT NULL;

ALTER TABLE EMPLOYEE
MODIFY JOB_CODE NOT NULL;

ALTER TABLE EMPLOYEE
MODIFY SAL_LEVEL NOT NULL;

ALTER TABLE NATIONAL
ADD CONSTRAINT NATIONAL_CODE_PK PRIMARY KEY (NATIONAL_CODE);

ALTER TABLE NATIONAL
DROP CONSTRAINT NATIONAL_CODE;

ALTER TABLE SAL_GRADE
ADD CONSTRAINT SAL_LEVEL_PK PRIMARY KEY (SAL_LEVEL);

-- 제약조건 확인
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMPLOYEE';